version: 2

os_version: &os_version
  macos:
  machine:
   xcode:
    version: "9.0"

jobs:
  lint:
    <<: *os_version
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Linting
          command: npm run lint
  
  mobile_functional_tests:
    <<: *os_version
    steps:
      - checkout
      - run:
          name: WDA Init
          command: git submodule update --init
      - run:
          name: Install
          command: npm install
      - run:
          name: Functional Tests - Web
          command: npm run mocha -- -t 480000 --recursive build/test/functional/web -g @skip-ci -i
          environmen:
            CI_METRICS: 1
            CI: 1
            REAL_DEVICE: 0
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - mobile_functional_tests:
          requires:
              - lint
             
    